### ISSUE TITLE
example input for python forecasting.py

### ISSUE THREAD

**Issue by Shicheng-Guo** [cyrusmaher/MutationEpiScore#2]
Dear Cyrus, 

I am wondering can you share an example/demo data for GISAID metadata file or the steps how to prepare this file? 

`python forecasting.py [GISAID metadata file] [Output folder]`

Thanks. 

Shicheng

**Comment by qianqli** [comment]
Dear Cyrus,

I am interested in your work here, and try to repeat it myself. I have a few questions regarding the data preparation steps. 

1, The GISAID data you used consists of 4,487,305 sequences, but I only got 4,477,734, is this because of the data update or
Do you do some extra work? 

2, The codon shape and entropy data (you prepared based on Manfredonia et al. 2020), could you give more detail about how you did this? There are three files from the link you give, DMS, SHAPE-invitro, and SHAPE-invivo. Do the variables codon1, 2, and 3 have relations to these?  If not,  how do you define the codon position1, 2, and 3?  What's more,  how do you prepare the data codon-shape (Is the "shape" the structure or the method used for the structure prediction?), and what is the data like?   PS: the .xml data files are the sequences and reactivity values, do you use them, and how?  

3, In the S1 table, the negative selection feature, how do you prepare this? Which algorithm and data do you use?

4, Data you used based on the other publication,  for some, you giving the source  (paper) means you use the original data without further calculation, while the source (this work) means you just use their models, am I right?  I notice that some papers only give limited data compared to the GISAID data and have no idea how to deal with the source data with different data sizes. Do you have some extra data preparation steps?

Thank you. 

Qianqian
